name: To demonistrate input variables
on:  
 workflow_dispatch:
   inputs:
     environment:
       description: to provide input variables
       required: true
       default: dev
jobs:
  printthevalue:
    runs-on: ubuntu-latest

    steps:
      - name: To print the environment value
        run: echo "Your app is connecting to the ${{ inputs.environment }}

        
    
