name: To demonistrate outputs
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.step1.outputs.name }}
    
    steps:
      - name: To generate the output value
        id: step1
        run : echo "name=Lenin" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name : To get output from the 1st Job
        run : echo "Result from job1 is ${{ needs.job1.outputs.result }}"
