name: simple pipeline
on: workflow_dispatch
jobs:
  compile:
    runs-on: ubuntu-latest
    steps: 
      - name: To compile the source code
        run: echo "Compiled the source code."
  test:
    runs-on: ubuntu-latest
    steps:
      - name: To test the source code
        run: echo "Tested the source code"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: To deploy the source code
        run: echo "Source code id deployed"
